# Eureka Server & Client Configuration
eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true

# To Enable all endpoints for Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  secret: noonewilleverguess
